name: Checking pull request gate pass
on:
  pull_request:
    branches:
      - [main]
jobs:
  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          token: ${{secrets.GA_TOKEN}}
          submodules: recursive
          lfs: false
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Lint checks
        run: ./gradlew -Pci --console=plain lintDebug
  spotless-check:
    name: Spotless Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          token: ${{secrets.GA_TOKEN}}
          submodules: recursive
          lfs: false
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Spotless check
        run: ./gradlew -Pci --console=plain spotlessCheck
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          token: ${{secrets.GA_TOKEN}}
          submodules: recursive
          lfs: false
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Unit tests
        run: ./gradlew -Pci --console=plain testDebugUnitTest


  instrumented-tests:
    name: Instrumentation tests
    runs-on: macOS-latest
    timeout-minutes: 60
    strategy:
      fail-fast: true
      matrix:
        api-level: [29]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          token: ${{secrets.GA_TOKEN}}
          submodules: recursive
          lfs: false
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      # Restore the cache.
      # Intentionally don't set 'restore-keys' so the cache never contains redundant dependencies.
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86
          script: ./gradlew :cache:connectedDebugAndroidTest :remote:connectedDebugAndroidTest :presentation:connectedDebugAndroidTest :ui:connectedDebugAndroidTest --no-parallel