name: Deploying to Playstore
on:
  push:
    tags:
      - '*'
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          token: ${{secrets.GA_TOKEN}}
          submodules: recursive
          lfs: false
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GA_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

  generate-changelog:
    name: Generate CHANGELOG.md
    runs-on: ubuntu-latest
    needs: [release]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          token: ${{secrets.GA_TOKEN}}
          submodules: recursive
          lfs: false
          fetch-depth: 0
      - uses: BobAnkh/auto-generate-changelog@master
        with:
          REPO_NAME: 'RowlandOti/E-CommerceApp-Merchant'
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PATH: '/CHANGELOG.md'
          COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
          TYPE: 'ci:Continuous Integration,test:Tests,feat:New Features,fix:Bug Fixes,lint:Code Style Fixes,docs:Documentation,refactor:Refactors,perf:Performance Improvements'

  deploy:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          token: ${{secrets.GA_TOKEN}}
          submodules: recursive
          lfs: false
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Cache Ruby - Bundler
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Configure Keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > keystore.jks
          echo "storeFile=keystore.jks" >> keystore.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> keystore.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.ANDROID_KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_STORE_PASSWORD }}

      - name: Create Google Play Config file
        run: |
          echo "$PLAYSTORE_SERVICES_CONFIG" > playstore_services_config.json.b64
          base64 -d -i playstore_services_config.json.b64 > ./.buildsystem/playstore_services_config.json
        env:
          PLAYSTORE_SERVICES_CONFIG: ${{ secrets.PLAYSTORE_SERVICES_CONFIG }}

      - name: Distribute app to Alpha track 🚀
        run: bundle exec fastlane deployAlpha